# API Configuration
api:
  base_url: "https://api.deepseek.com/v1"
  model: "deepseek-reasoner"

# Model Parameters
model:
  max_tokens: 2000
  timeout: 30

# SQL Configuration
sql:
  dialect: "hive"
  theme: "monokai"

# Session Configuration
session:
  timeout: 300
  history_size: 1000 